### ISSUE TITLE
Need Sharepoint Help

### ISSUE THREAD

**Issue by TonyValenti** [nils-org/fluentcamlgen#112]
Hi @nils-a -
I need some help with Sharepoint's API and I figured you might be an expert.  Can I hire you for a few hours?
If so, would you grab a time with me?
[General Meeting](https://calendly.com/tv--15/general_meeting)

I'm trying to grab all fields of all objects in a collection.
I was using ```/_api/web/GetListUsingPath(DecodedUrl=@a1)/items``` but ran into the query string limit.

I think I need to switch to ```/_api/web/GetListUsingPath(DecodedUrl=@a1)/getitems``` but I dont understand the request structure.

Can you help?

**Comment by TonyValenti** [comment]
Any chance I could buy a few hours of your time?

**Comment by nils-a** [comment]
Sorry, I don't do SharePoint consulting outside my employer's business.
